#!/bin/bash

#validando que el usuario que ejecuta este guion sea del grupo de usuario root
if [ `id -g` -ne 0 ]
then
  echo "Usage:  ./$0 root group"
  exit $E_BADARGS
fi


if [ -z $1 ] 
then
    echo "please supply username"
    exit 1
fi
rm -fr /home/$1
#rm  /etc/apache2/sites-available/$1 
deluser $1
delgroup $1
a2dissite $1
/etc/init.d/apache2 reload
